-- STF Group ERP - Complete Fresh MySQL/MariaDB Install
-- Generated from the Laravel 12 production migrations and production seed.
-- Fresh database only. No demo employees, vehicles, documents, notifications, or audit records.
SET NAMES utf8mb4;
SET time_zone = "+03:00";
SET FOREIGN_KEY_CHECKS = 0;

create table `migrations` (`id` int unsigned not null auto_increment primary key, `migration` varchar(255) not null, `batch` int not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
create table `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `email_verified_at` timestamp null, `password` varchar(255) not null, `status` varchar(20) not null default 'active', `all_companies` tinyint(1) not null default '0', `profile_photo_path` varchar(255) null, `last_login_at` timestamp null, `password_changed_at` timestamp null, `force_password_change` tinyint(1) not null default '1', `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `users` add unique `users_email_unique`(`email`);
alter table `users` add index `users_status_index`(`status`);
create table `password_reset_tokens` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null, primary key (`email`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
create table `sessions` (`id` varchar(255) not null, `user_id` bigint unsigned null, `ip_address` varchar(45) null, `user_agent` text null, `payload` longtext not null, `last_activity` int not null, primary key (`id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `sessions` add index `sessions_user_id_index`(`user_id`);
alter table `sessions` add index `sessions_last_activity_index`(`last_activity`);
create table `cache` (`key` varchar(255) not null, `value` mediumtext not null, `expiration` int not null, primary key (`key`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `cache` add index `cache_expiration_index`(`expiration`);
create table `cache_locks` (`key` varchar(255) not null, `owner` varchar(255) not null, `expiration` int not null, primary key (`key`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `cache_locks` add index `cache_locks_expiration_index`(`expiration`);
create table `jobs` (`id` bigint unsigned not null auto_increment primary key, `queue` varchar(255) not null, `payload` longtext not null, `attempts` tinyint unsigned not null, `reserved_at` int unsigned null, `available_at` int unsigned not null, `created_at` int unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `jobs` add index `jobs_queue_index`(`queue`);
create table `job_batches` (`id` varchar(255) not null, `name` varchar(255) not null, `total_jobs` int not null, `pending_jobs` int not null, `failed_jobs` int not null, `failed_job_ids` longtext not null, `options` mediumtext null, `cancelled_at` int null, `created_at` int not null, `finished_at` int null, primary key (`id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
create table `failed_jobs` (`id` bigint unsigned not null auto_increment primary key, `uuid` varchar(255) not null, `connection` text not null, `queue` text not null, `payload` longtext not null, `exception` longtext not null, `failed_at` timestamp not null default CURRENT_TIMESTAMP) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `failed_jobs` add unique `failed_jobs_uuid_unique`(`uuid`);
create table `permissions` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `guard_name` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `permissions` add unique `permissions_name_guard_name_unique`(`name`, `guard_name`);
create table `roles` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `guard_name` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `roles` add unique `roles_name_guard_name_unique`(`name`, `guard_name`);
create table `model_has_permissions` (`permission_id` bigint unsigned not null, `model_type` varchar(255) not null, `model_id` bigint unsigned not null, primary key (`permission_id`, `model_id`, `model_type`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `model_has_permissions` add index `model_has_permissions_model_id_model_type_index`(`model_id`, `model_type`);
alter table `model_has_permissions` add constraint `model_has_permissions_permission_id_foreign` foreign key (`permission_id`) references `permissions` (`id`) on delete cascade;
create table `model_has_roles` (`role_id` bigint unsigned not null, `model_type` varchar(255) not null, `model_id` bigint unsigned not null, primary key (`role_id`, `model_id`, `model_type`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `model_has_roles` add index `model_has_roles_model_id_model_type_index`(`model_id`, `model_type`);
alter table `model_has_roles` add constraint `model_has_roles_role_id_foreign` foreign key (`role_id`) references `roles` (`id`) on delete cascade;
create table `role_has_permissions` (`permission_id` bigint unsigned not null, `role_id` bigint unsigned not null, primary key (`permission_id`, `role_id`)) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `role_has_permissions` add constraint `role_has_permissions_permission_id_foreign` foreign key (`permission_id`) references `permissions` (`id`) on delete cascade;
alter table `role_has_permissions` add constraint `role_has_permissions_role_id_foreign` foreign key (`role_id`) references `roles` (`id`) on delete cascade;
create table `personal_access_tokens` (`id` bigint unsigned not null auto_increment primary key, `tokenable_type` varchar(255) not null, `tokenable_id` bigint unsigned not null, `name` text not null, `token` varchar(64) not null, `abilities` text null, `last_used_at` timestamp null, `expires_at` timestamp null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `personal_access_tokens` add index `personal_access_tokens_tokenable_type_tokenable_id_index`(`tokenable_type`, `tokenable_id`);
alter table `personal_access_tokens` add unique `personal_access_tokens_token_unique`(`token`);
alter table `personal_access_tokens` add index `personal_access_tokens_expires_at_index`(`expires_at`);
create table `companies` (`id` bigint unsigned not null auto_increment primary key, `code` varchar(30) not null, `name` varchar(255) not null, `cr_number` varchar(255) null, `tax_number` varchar(255) null, `computer_card_number` varchar(255) null, `email` varchar(255) null, `phone` varchar(40) null, `address` text null, `po_box` varchar(50) null, `city` varchar(100) not null default 'Doha', `country` varchar(100) not null default 'Qatar', `logo_path` varchar(255) null, `is_active` tinyint(1) not null default '1', `reminder_days` json null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `companies` add unique `companies_code_unique`(`code`);
alter table `companies` add index `companies_is_active_index`(`is_active`);
create table `company_user` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned not null, `user_id` bigint unsigned not null, `is_primary` tinyint(1) not null default '0', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `company_user` add constraint `company_user_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete cascade;
alter table `company_user` add constraint `company_user_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade;
alter table `company_user` add unique `company_user_company_id_user_id_unique`(`company_id`, `user_id`);
alter table `company_user` add index `company_user_user_id_is_primary_index`(`user_id`, `is_primary`);
create table `departments` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned not null, `name` varchar(255) not null, `code` varchar(30) not null, `manager_user_id` bigint unsigned null, `is_active` tinyint(1) not null default '1', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `departments` add constraint `departments_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete cascade;
alter table `departments` add constraint `departments_manager_user_id_foreign` foreign key (`manager_user_id`) references `users` (`id`) on delete set null;
alter table `departments` add unique `departments_company_id_code_unique`(`company_id`, `code`);
alter table `departments` add index `departments_company_id_is_active_index`(`company_id`, `is_active`);
create table `designations` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned not null, `department_id` bigint unsigned null, `name` varchar(255) not null, `code` varchar(30) null, `is_active` tinyint(1) not null default '1', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `designations` add constraint `designations_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete cascade;
alter table `designations` add constraint `designations_department_id_foreign` foreign key (`department_id`) references `departments` (`id`) on delete set null;
alter table `designations` add index `designations_company_id_is_active_index`(`company_id`, `is_active`);
create table `employees` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned not null, `department_id` bigint unsigned null, `designation_id` bigint unsigned null, `internal_id` varchar(60) null, `employee_code` varchar(60) not null, `full_name` varchar(255) not null, `profile_photo_path` varchar(255) null, `nationality` varchar(100) null, `date_of_birth` date null, `gender` varchar(20) null, `mobile` varchar(40) null, `alternative_mobile` varchar(40) null, `email` varchar(255) null, `qatar_address` text null, `home_country_address` text null, `emergency_contact_name` varchar(255) null, `emergency_contact_relationship` varchar(100) null, `emergency_contact_phone` varchar(40) null, `joining_date` date null, `basic_salary` decimal(12, 2) not null default '0', `allowances` decimal(12, 2) not null default '0', `noc_status` varchar(100) null, `trade_specialization` varchar(255) null, `salary_payment_mode` varchar(100) null, `previous_company_name` varchar(255) null, `bank_wallet_details` text null, `status` varchar(30) not null default 'active', `notes` text null, `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `employees` add constraint `employees_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete restrict;
alter table `employees` add constraint `employees_department_id_foreign` foreign key (`department_id`) references `departments` (`id`) on delete set null;
alter table `employees` add constraint `employees_designation_id_foreign` foreign key (`designation_id`) references `designations` (`id`) on delete set null;
alter table `employees` add constraint `employees_created_by_foreign` foreign key (`created_by`) references `users` (`id`) on delete set null;
alter table `employees` add constraint `employees_updated_by_foreign` foreign key (`updated_by`) references `users` (`id`) on delete set null;
alter table `employees` add unique `employees_company_id_employee_code_unique`(`company_id`, `employee_code`);
alter table `employees` add index `employees_company_id_department_id_status_index`(`company_id`, `department_id`, `status`);
alter table `employees` add index `employees_full_name_mobile_index`(`full_name`, `mobile`);
alter table `employees` add index `employees_status_index`(`status`);
create table `vehicles` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned not null, `internal_vehicle_id` varchar(60) not null, `vehicle_name` varchar(255) null, `vehicle_number` varchar(80) not null, `plate_number` varchar(80) not null, `make` varchar(100) null, `model` varchar(100) null, `year` smallint unsigned null, `colour` varchar(60) null, `chassis_number` varchar(120) null, `engine_number` varchar(120) null, `vehicle_type` varchar(80) null, `assigned_driver_id` bigint unsigned null, `secondary_driver_id` bigint unsigned null, `ownership_type` varchar(30) not null default 'owned', `registration_date` date null, `status` varchar(30) not null default 'active', `notes` text null, `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `vehicles` add constraint `vehicles_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete restrict;
alter table `vehicles` add constraint `vehicles_assigned_driver_id_foreign` foreign key (`assigned_driver_id`) references `employees` (`id`) on delete set null;
alter table `vehicles` add constraint `vehicles_secondary_driver_id_foreign` foreign key (`secondary_driver_id`) references `employees` (`id`) on delete set null;
alter table `vehicles` add constraint `vehicles_created_by_foreign` foreign key (`created_by`) references `users` (`id`) on delete set null;
alter table `vehicles` add constraint `vehicles_updated_by_foreign` foreign key (`updated_by`) references `users` (`id`) on delete set null;
alter table `vehicles` add unique `vehicles_company_id_internal_vehicle_id_unique`(`company_id`, `internal_vehicle_id`);
alter table `vehicles` add index `vehicles_company_id_plate_number_index`(`company_id`, `plate_number`);
alter table `vehicles` add index `vehicles_status_index`(`status`);
create table `vehicle_assignments` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned not null, `vehicle_id` bigint unsigned not null, `employee_id` bigint unsigned not null, `assignment_type` varchar(20) not null default 'primary', `assigned_date` date not null, `unassigned_date` date null, `notes` text null, `assigned_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `vehicle_assignments` add constraint `vehicle_assignments_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete cascade;
alter table `vehicle_assignments` add constraint `vehicle_assignments_vehicle_id_foreign` foreign key (`vehicle_id`) references `vehicles` (`id`) on delete cascade;
alter table `vehicle_assignments` add constraint `vehicle_assignments_employee_id_foreign` foreign key (`employee_id`) references `employees` (`id`) on delete restrict;
alter table `vehicle_assignments` add constraint `vehicle_assignments_assigned_by_foreign` foreign key (`assigned_by`) references `users` (`id`) on delete set null;
alter table `vehicle_assignments` add index `vehicle_assignments_vehicle_id_unassigned_date_index`(`vehicle_id`, `unassigned_date`);
alter table `vehicle_assignments` add index `vehicle_assignments_employee_id_unassigned_date_index`(`employee_id`, `unassigned_date`);
create table `stored_files` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned null, `disk` varchar(40) not null default 'local', `path` varchar(255) not null, `original_name` varchar(255) not null, `mime_type` varchar(100) not null, `size_bytes` bigint unsigned not null, `sha256` char(64) not null, `uploaded_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `stored_files` add constraint `stored_files_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete cascade;
alter table `stored_files` add constraint `stored_files_uploaded_by_foreign` foreign key (`uploaded_by`) references `users` (`id`) on delete set null;
alter table `stored_files` add unique `stored_files_path_unique`(`path`);
alter table `stored_files` add index `stored_files_sha256_index`(`sha256`);
create table `document_types` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `code` varchar(80) not null, `owner_type` varchar(20) not null, `document_number_required` tinyint(1) not null default '1', `issue_date_required` tinyint(1) not null default '0', `expiry_date_required` tinyint(1) not null default '1', `file_required` tinyint(1) not null default '0', `reminder_enabled` tinyint(1) not null default '1', `custom_reminder_days` json null, `alert_lead_days` smallint unsigned not null default '30', `default_validity_months` smallint unsigned null, `is_active` tinyint(1) not null default '1', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `document_types` add unique `document_types_code_unique`(`code`);
alter table `document_types` add index `document_types_owner_type_index`(`owner_type`);
alter table `document_types` add index `document_types_is_active_index`(`is_active`);
create table `documents` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned not null, `owner_type` varchar(20) not null, `owner_id` bigint unsigned not null, `document_type_id` bigint unsigned not null, `document_number` varchar(255) null, `issue_date` date null, `expiry_date` date null, `issuing_country` varchar(100) null, `issuing_authority` varchar(255) null, `status` varchar(30) not null default 'active', `notes` text null, `current_file_id` bigint unsigned null, `reminder_enabled` tinyint(1) not null default '1', `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `documents` add constraint `documents_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete restrict;
alter table `documents` add constraint `documents_document_type_id_foreign` foreign key (`document_type_id`) references `document_types` (`id`) on delete restrict;
alter table `documents` add constraint `documents_current_file_id_foreign` foreign key (`current_file_id`) references `stored_files` (`id`) on delete set null;
alter table `documents` add constraint `documents_created_by_foreign` foreign key (`created_by`) references `users` (`id`) on delete set null;
alter table `documents` add constraint `documents_updated_by_foreign` foreign key (`updated_by`) references `users` (`id`) on delete set null;
alter table `documents` add index `documents_company_id_owner_type_owner_id_index`(`company_id`, `owner_type`, `owner_id`);
alter table `documents` add index `documents_company_id_document_type_id_expiry_date_index`(`company_id`, `document_type_id`, `expiry_date`);
alter table `documents` add index `documents_document_number_index`(`document_number`);
create table `document_renewals` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned not null, `document_id` bigint unsigned not null, `previous_document_number` varchar(255) null, `previous_issue_date` date null, `previous_expiry_date` date null, `previous_file_id` bigint unsigned null, `new_document_number` varchar(255) null, `new_issue_date` date null, `new_expiry_date` date null, `new_file_id` bigint unsigned null, `renewed_at` timestamp not null, `renewed_by` bigint unsigned null, `notes` text null, `change_reason` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `document_renewals` add constraint `document_renewals_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete cascade;
alter table `document_renewals` add constraint `document_renewals_document_id_foreign` foreign key (`document_id`) references `documents` (`id`) on delete cascade;
alter table `document_renewals` add constraint `document_renewals_previous_file_id_foreign` foreign key (`previous_file_id`) references `stored_files` (`id`) on delete set null;
alter table `document_renewals` add constraint `document_renewals_new_file_id_foreign` foreign key (`new_file_id`) references `stored_files` (`id`) on delete set null;
alter table `document_renewals` add constraint `document_renewals_renewed_by_foreign` foreign key (`renewed_by`) references `users` (`id`) on delete set null;
alter table `document_renewals` add index `document_renewals_document_id_renewed_at_index`(`document_id`, `renewed_at`);
create table `reminder_rules` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned null, `document_type_id` bigint unsigned null, `reminder_days` json not null, `channels` json not null, `recipients` json not null, `is_active` tinyint(1) not null default '1', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `reminder_rules` add constraint `reminder_rules_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete cascade;
alter table `reminder_rules` add constraint `reminder_rules_document_type_id_foreign` foreign key (`document_type_id`) references `document_types` (`id`) on delete cascade;
alter table `reminder_rules` add unique `reminder_rules_company_id_document_type_id_unique`(`company_id`, `document_type_id`);
create table `notification_templates` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned null, `document_type_id` bigint unsigned null, `name` varchar(255) not null, `channel` varchar(20) not null, `language` varchar(10) not null default 'en', `email_subject` varchar(255) null, `message_body` text not null, `is_active` tinyint(1) not null default '1', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `notification_templates` add constraint `notification_templates_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete cascade;
alter table `notification_templates` add constraint `notification_templates_document_type_id_foreign` foreign key (`document_type_id`) references `document_types` (`id`) on delete cascade;
alter table `notification_templates` add index `notification_templates_channel_is_active_index`(`channel`, `is_active`);
create table `notification_logs` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned not null, `document_id` bigint unsigned null, `owner_type` varchar(20) null, `owner_id` bigint unsigned null, `document_type_id` bigint unsigned null, `recipient_name` varchar(255) null, `recipient_contact` varchar(255) not null, `channel` varchar(20) not null, `provider` varchar(100) null, `provider_message_id` varchar(255) null, `email_subject` varchar(255) null, `message_body` text not null, `expiry_date` date null, `reminder_day` smallint null, `scheduled_date` date null, `status` varchar(30) not null default 'queued', `failure_reason` text null, `retry_count` tinyint unsigned not null default '0', `queued_at` timestamp null, `sent_at` timestamp null, `delivered_at` timestamp null, `idempotency_key` varchar(190) not null, `provider_payload` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `notification_logs` add constraint `notification_logs_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete cascade;
alter table `notification_logs` add constraint `notification_logs_document_id_foreign` foreign key (`document_id`) references `documents` (`id`) on delete set null;
alter table `notification_logs` add constraint `notification_logs_document_type_id_foreign` foreign key (`document_type_id`) references `document_types` (`id`) on delete set null;
alter table `notification_logs` add index `notification_logs_company_id_channel_created_at_index`(`company_id`, `channel`, `created_at`);
alter table `notification_logs` add index `notification_logs_document_id_scheduled_date_index`(`document_id`, `scheduled_date`);
alter table `notification_logs` add index `notification_logs_status_index`(`status`);
alter table `notification_logs` add unique `notification_logs_idempotency_key_unique`(`idempotency_key`);
create table `audit_logs` (`id` bigint unsigned not null auto_increment primary key, `user_id` bigint unsigned null, `company_id` bigint unsigned null, `action` varchar(100) not null, `module` varchar(80) not null, `record_type` varchar(255) null, `record_id` varchar(80) null, `previous_values` json null, `new_values` json null, `ip_address` varchar(45) null, `user_agent` text null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `audit_logs` add constraint `audit_logs_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete set null;
alter table `audit_logs` add constraint `audit_logs_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete set null;
alter table `audit_logs` add index `audit_logs_module_created_at_index`(`module`, `created_at`);
alter table `audit_logs` add index `audit_logs_company_id_created_at_index`(`company_id`, `created_at`);
create table `system_settings` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned null, `key` varchar(100) not null, `value` json not null, `is_secret` tinyint(1) not null default '0', `updated_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `system_settings` add constraint `system_settings_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete cascade;
alter table `system_settings` add constraint `system_settings_updated_by_foreign` foreign key (`updated_by`) references `users` (`id`) on delete set null;
alter table `system_settings` add unique `system_settings_company_id_key_unique`(`company_id`, `key`);
create table `import_batches` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned not null, `user_id` bigint unsigned not null, `type` varchar(50) not null, `status` varchar(30) not null default 'preview', `total_rows` int unsigned not null default '0', `valid_rows` int unsigned not null default '0', `invalid_rows` int unsigned not null default '0', `created_rows` int unsigned not null default '0', `updated_rows` int unsigned not null default '0', `column_mapping` json null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `import_batches` add constraint `import_batches_company_id_foreign` foreign key (`company_id`) references `companies` (`id`) on delete cascade;
alter table `import_batches` add constraint `import_batches_user_id_foreign` foreign key (`user_id`) references `users` (`id`) on delete cascade;
create table `import_rows` (`id` bigint unsigned not null auto_increment primary key, `import_batch_id` bigint unsigned not null, `row_number` int unsigned not null, `raw_data` json not null, `normalized_data` json null, `errors` json null, `status` varchar(30) not null default 'pending', `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci';
alter table `import_rows` add constraint `import_rows_import_batch_id_foreign` foreign key (`import_batch_id`) references `import_batches` (`id`) on delete cascade;
alter table `import_rows` add unique `import_rows_import_batch_id_row_number_unique`(`import_batch_id`, `row_number`);

-- Production seed data
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (1, 'dashboard.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (2, 'companies.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (3, 'companies.manage', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (4, 'departments.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (5, 'departments.manage', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (6, 'designations.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (7, 'designations.manage', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (8, 'employees.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (9, 'employees.create', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (10, 'employees.update', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (11, 'employees.archive', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (12, 'employees.restore', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (13, 'documents.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (14, 'documents.create', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (15, 'documents.update', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (16, 'documents.archive', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (17, 'documents.restore', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (18, 'documents.renew', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (19, 'document_types.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (20, 'document_types.manage', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (21, 'vehicles.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (22, 'vehicles.manage', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (23, 'vehicles.archive', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (24, 'vehicles.restore', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (25, 'company_documents.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (26, 'company_documents.manage', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (27, 'notifications.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (28, 'notifications.manage', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (29, 'notifications.retry', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (30, 'notifications.run', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (31, 'templates.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (32, 'templates.manage', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (33, 'reports.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (34, 'reports.export', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (35, 'imports.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (36, 'imports.create', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (37, 'audit.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (38, 'settings.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (39, 'settings.manage', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (40, 'users.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (41, 'users.manage', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (42, 'roles.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (43, 'roles.manage', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (44, 'files.view', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (45, 'files.upload', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (46, 'files.download', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `roles` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (1, 'Super Admin', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `roles` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (2, 'HR', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `roles` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (3, 'Manager', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `roles` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (4, 'Accountant', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `roles` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES (5, 'Read-Only User', 'web', '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (1, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (1, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (1, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (1, 4);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (1, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (2, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (2, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (2, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (2, 4);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (2, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (3, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (4, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (4, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (4, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (4, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (5, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (6, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (6, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (6, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (6, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (7, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (8, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (8, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (8, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (8, 4);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (8, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (9, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (9, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (10, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (10, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (10, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (11, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (11, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (12, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (12, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (13, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (13, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (13, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (13, 4);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (13, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (14, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (14, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (14, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (15, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (15, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (15, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (16, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (16, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (17, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (17, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (18, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (18, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (18, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (19, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (19, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (19, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (19, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (20, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (21, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (21, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (21, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (21, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (22, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (22, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (23, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (24, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (25, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (25, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (25, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (25, 4);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (25, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (26, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (26, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (27, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (27, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (27, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (27, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (28, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (29, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (30, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (30, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (31, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (31, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (31, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (32, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (33, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (33, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (33, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (33, 4);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (33, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (34, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (34, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (34, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (34, 4);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (35, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (35, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (36, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (36, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (37, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (37, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (38, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (39, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (40, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (41, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (42, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (43, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (44, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (44, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (44, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (44, 4);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (44, 5);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (45, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (45, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (45, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (46, 1);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (46, 2);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (46, 3);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (46, 4);
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES (46, 5);
INSERT INTO `companies` (`id`, `code`, `name`, `cr_number`, `tax_number`, `computer_card_number`, `email`, `phone`, `address`, `po_box`, `city`, `country`, `logo_path`, `is_active`, `reminder_days`, `created_at`, `updated_at`, `deleted_at`) VALUES (1, 'SAS', 'SEAF AL SAFER LIMOUSINE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Doha', 'Qatar', NULL, 1, '[30,15,10,7,3,1,0]', '2026-07-25 21:25:17', '2026-07-25 21:25:17', NULL);
INSERT INTO `companies` (`id`, `code`, `name`, `cr_number`, `tax_number`, `computer_card_number`, `email`, `phone`, `address`, `po_box`, `city`, `country`, `logo_path`, `is_active`, `reminder_days`, `created_at`, `updated_at`, `deleted_at`) VALUES (2, 'TFC', 'TRUST AND FIRST TRADING AND CONTRACTING', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Doha', 'Qatar', NULL, 1, '[30,15,10,7,3,1,0]', '2026-07-25 21:25:17', '2026-07-25 21:25:17', NULL);
INSERT INTO `companies` (`id`, `code`, `name`, `cr_number`, `tax_number`, `computer_card_number`, `email`, `phone`, `address`, `po_box`, `city`, `country`, `logo_path`, `is_active`, `reminder_days`, `created_at`, `updated_at`, `deleted_at`) VALUES (3, 'TFD', 'TRUST AND FIRST DELIVERY SERVICES', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Doha', 'Qatar', NULL, 1, '[30,15,10,7,3,1,0]', '2026-07-25 21:25:17', '2026-07-25 21:25:17', NULL);
INSERT INTO `companies` (`id`, `code`, `name`, `cr_number`, `tax_number`, `computer_card_number`, `email`, `phone`, `address`, `po_box`, `city`, `country`, `logo_path`, `is_active`, `reminder_days`, `created_at`, `updated_at`, `deleted_at`) VALUES (4, 'FST', 'FLY SAFE TRAVELS AND TOURS', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Doha', 'Qatar', NULL, 1, '[30,15,10,7,3,1,0]', '2026-07-25 21:25:17', '2026-07-25 21:25:17', NULL);
INSERT INTO `companies` (`id`, `code`, `name`, `cr_number`, `tax_number`, `computer_card_number`, `email`, `phone`, `address`, `po_box`, `city`, `country`, `logo_path`, `is_active`, `reminder_days`, `created_at`, `updated_at`, `deleted_at`) VALUES (5, 'TFG', 'TRUST AND FIRST TRADING (GARAGE)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Doha', 'Qatar', NULL, 1, '[30,15,10,7,3,1,0]', '2026-07-25 21:25:17', '2026-07-25 21:25:17', NULL);
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (1, 'QID', 'qid', 'employee', 1, 0, 1, 0, 1, '[30,15,10,7,3,1,0]', 15, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (2, 'Passport', 'passport', 'employee', 1, 0, 1, 0, 1, '[30,15,10,7,3,1,0]', 90, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (3, 'Visa', 'visa', 'employee', 1, 0, 1, 0, 1, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (4, 'Driving License', 'driving-license', 'employee', 1, 0, 1, 0, 1, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (5, 'Health Card', 'health-card', 'employee', 0, 0, 0, 0, 1, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (6, 'Employment Contract', 'employment-contract', 'employee', 0, 0, 0, 0, 0, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (7, 'Labour Contract', 'labour-contract', 'employee', 0, 0, 0, 0, 0, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (8, 'Istimara', 'istimara', 'vehicle', 1, 0, 1, 0, 1, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (9, 'Vehicle Insurance', 'vehicle-insurance', 'vehicle', 1, 0, 1, 0, 1, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (10, 'Vehicle Inspection', 'vehicle-inspection', 'vehicle', 1, 0, 1, 0, 1, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (11, 'Limousine Permit', 'limousine-permit', 'vehicle', 1, 0, 1, 0, 1, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (12, 'Trade License', 'trade-license', 'company', 1, 0, 1, 0, 1, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (13, 'Commercial Registration', 'commercial-registration', 'company', 1, 0, 1, 0, 1, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (14, 'Computer Card', 'computer-card', 'company', 1, 0, 1, 0, 1, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (15, 'Municipality License', 'municipality-license', 'company', 1, 0, 1, 0, 1, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `document_types` (`id`, `name`, `code`, `owner_type`, `document_number_required`, `issue_date_required`, `expiry_date_required`, `file_required`, `reminder_enabled`, `custom_reminder_days`, `alert_lead_days`, `default_validity_months`, `is_active`, `created_at`, `updated_at`) VALUES (16, 'Establishment Card', 'establishment-card', 'company', 1, 0, 1, 0, 1, '[30,15,10,7,3,1,0]', 30, NULL, 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `system_settings` (`id`, `company_id`, `key`, `value`, `is_secret`, `updated_by`, `created_at`, `updated_at`) VALUES (1, NULL, 'application', '{"timezone":"Asia\\/Qatar","globalReminderDays":[30,15,10,7,3,1,0],"defaultFileMaxSizeMb":5,"autoExpiryScanEnabled":true,"providerConfig":{"emailEnabled":true,"smsEnabled":true,"whatsappEnabled":true,"mockMode":true}}', 0, NULL, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `notification_templates` (`id`, `company_id`, `document_type_id`, `name`, `channel`, `language`, `email_subject`, `message_body`, `is_active`, `created_at`, `updated_at`) VALUES (1, NULL, NULL, 'Default Expiry Email', 'email', 'en', '{DocumentType} expiry reminder', 'Dear {EmployeeName}, your {DocumentType} will expire on {ExpiryDate}. Please renew it before expiry. STF Group HR Department', 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `notification_templates` (`id`, `company_id`, `document_type_id`, `name`, `channel`, `language`, `email_subject`, `message_body`, `is_active`, `created_at`, `updated_at`) VALUES (2, NULL, NULL, 'Default Expiry SMS', 'sms', 'en', NULL, 'Dear {EmployeeName}, your {DocumentType} will expire on {ExpiryDate}. Please renew it. STF Group HR', 1, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `status`, `all_companies`, `profile_photo_path`, `last_login_at`, `password_changed_at`, `force_password_change`, `remember_token`, `created_at`, `updated_at`) VALUES (1, 'STF Group Administrator', 'admin@trustgroup.local', NULL, '$2y$12$h0UyyloElBuLwxIV2i8QMu13Ufz9WfKa6CbR1Hg7y1L77H1WfiX/y', 'active', 1, NULL, NULL, NULL, 1, NULL, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES (1, 'App\\Models\\User', 1);
INSERT INTO `company_user` (`id`, `company_id`, `user_id`, `is_primary`, `created_at`, `updated_at`) VALUES (1, 1, 1, 0, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `company_user` (`id`, `company_id`, `user_id`, `is_primary`, `created_at`, `updated_at`) VALUES (2, 2, 1, 0, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `company_user` (`id`, `company_id`, `user_id`, `is_primary`, `created_at`, `updated_at`) VALUES (3, 3, 1, 0, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `company_user` (`id`, `company_id`, `user_id`, `is_primary`, `created_at`, `updated_at`) VALUES (4, 4, 1, 0, '2026-07-25 21:25:17', '2026-07-25 21:25:17');
INSERT INTO `company_user` (`id`, `company_id`, `user_id`, `is_primary`, `created_at`, `updated_at`) VALUES (5, 5, 1, 0, '2026-07-25 21:25:17', '2026-07-25 21:25:17');

INSERT INTO `migrations` (`migration`, `batch`) VALUES
('0001_01_01_000000_create_users_table', 1),
('0001_01_01_000001_create_cache_table', 1),
('0001_01_01_000002_create_jobs_table', 1),
('2026_07_24_145509_create_permission_tables', 1),
('2026_07_24_145512_create_personal_access_tokens_table', 1),
('2026_07_24_145520_create_erp_tables', 1),
('2026_08_17_090000_add_stf_group_module_columns', 1);
SET FOREIGN_KEY_CHECKS = 1;

-- Verification: 33 tables; employees=0, vehicles=0, documents=0, notification_logs=0.
