-- Safe one-time upgrade for an existing STF Group ERP database.
-- Import this file in phpMyAdmin. It does not remove existing business data.
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE IF NOT EXISTS `accounting_accounts` (`id` bigint unsigned not null auto_increment primary key, `company_id` bigint unsigned not null, `employee_id` bigint unsigned null, `vehicle_id` bigint unsigned null, `account_type` varchar(40) not null, `title` varchar(255) not null, `reference_no` varchar(100) null, `start_date` date null, `end_date` date null, `amount` decimal(12,2) not null default 0, `total_amount` decimal(12,2) null, `down_payment_percent` decimal(5,2) null, `interest_percent` decimal(5,2) null, `program_months` int unsigned null, `status` varchar(30) not null default 'active', `details` json null, `notes` text null, `created_by` bigint unsigned null, `updated_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null);
ALTER TABLE `accounting_accounts` ADD INDEX `accounting_accounts_company_type_status_idx` (`company_id`,`account_type`,`status`);
CREATE TABLE IF NOT EXISTS `accounting_payments` (`id` bigint unsigned not null auto_increment primary key, `accounting_account_id` bigint unsigned not null, `payment_date` date null, `due_date` date null, `period_label` varchar(100) null, `amount_due` decimal(12,2) not null default 0, `amount_paid` decimal(12,2) not null default 0, `voucher_no` varchar(100) null, `payment_method` varchar(50) null, `status` varchar(20) not null default 'due', `notes` text null, `created_by` bigint unsigned null, `created_at` timestamp null, `updated_at` timestamp null);
ALTER TABLE `accounting_payments` ADD INDEX `accounting_payments_account_status_date_idx` (`accounting_account_id`,`status`,`payment_date`);
INSERT IGNORE INTO `permissions` (`name`,`guard_name`,`created_at`,`updated_at`) VALUES ('accounting.view','web',NOW(),NOW()),('accounting.manage','web',NOW(),NOW()),('accounting.payments.manage','web',NOW(),NOW());
INSERT IGNORE INTO `role_has_permissions` (`permission_id`,`role_id`) SELECT p.id,r.id FROM permissions p CROSS JOIN roles r WHERE p.name IN ('accounting.view','accounting.manage','accounting.payments.manage') AND r.name IN ('Super Admin','HR','Accountant');
INSERT IGNORE INTO `role_has_permissions` (`permission_id`,`role_id`) SELECT p.id,r.id FROM permissions p CROSS JOIN roles r WHERE p.name='accounting.view' AND r.name='Read-Only User';
INSERT IGNORE INTO `migrations` (`migration`,`batch`) VALUES ('2026_09_12_090000_create_accounting_tables', (SELECT COALESCE(MAX(batch),0)+1 FROM (SELECT batch FROM migrations) AS m));
SET FOREIGN_KEY_CHECKS = 1;
