[program:stf-group-erp-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /home/CPANEL_USER/stf-group-erp/backend/artisan queue:work database --sleep=3 --tries=3 --backoff=60 --timeout=120
directory=/home/CPANEL_USER/stf-group-erp/backend
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=CPANEL_USER
numprocs=1
redirect_stderr=true
stdout_logfile=/home/CPANEL_USER/stf-group-erp/backend/storage/logs/worker.log
stopwaitsecs=130
